version: '3.8'

services:
  nginx:
    container_name: rep-nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ../.:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - rep-php
      - mysql-db
  mysql-db:
    container_name: rep-mysql-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '4306:3306'
    volumes:
      - db-data:/var/lib/mysql
  rep-php:
    container_name: rep-php
    build:
      context: ./php
    expose:
      - '9000'
    volumes:
      - ../.:/var/www/app
    depends_on:
      - mysql-db

volumes:
  db-data:
